import type { Metadata } from "next";
import "./globals.css";
import RootLayout from "@/components/layout/root-layout";

export const metadata: Metadata = {
  title: "Team Management App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <RootLayout>{children}</RootLayout>;
}
